-- src/shared/ZombieConfig.luau
local ZombieConfig = {
    ["Zombie"] = {
        Id = "Zombie",
        Name = "Zombie",
        HP = 200,
        Attack = 100,
        Speed = 1.6,
        AttackRange = 3,
        AttackInterval = 1,
        Anims = {
            Idle = "rbxassetid://103252167598562",
            Walk = "rbxassetid://110893261547291",
            Bend = "rbxassetid://131459040784217",
            Eat  = "rbxassetid://119641402238824",
            Rise = "rbxassetid://116948729939997",
        }
    },
    ["DancingZombie"] = {
        Id = "DancingZombie",
        Name = "Dancing Zombie",
        HP = 200,
        Attack = 100,
        Speed = 1.6,
        AttackRange = 3,
        AttackInterval = 1,
        Anims = {
            Idle = "rbxassetid://103252167598562",
            Walk = "rbxassetid://110893261547291",
            Bend = "rbxassetid://131459040784217",
            Eat  = "rbxassetid://119641402238824",
            Rise = "rbxassetid://116948729939997",
        }
    },
    ["ConeheadZombie"] = {
        Id = "ConeheadZombie",
        Name = "Conehead Zombie",
        HP = 500,
        Attack = 150,
        Speed = 1.6,
        AttackRange = 3,
        AttackInterval = 1,
        Anims = {
           Idle = "rbxassetid://103252167598562",
            Walk = "rbxassetid://110893261547291",
            Bend = "rbxassetid://131459040784217",
            Eat  = "rbxassetid://119641402238824",
            Rise = "rbxassetid://116948729939997",
        }
    },
    ["BucketheadZombie"] = {
        Id = "BucketheadZombie",
        Name = "Buckethead Zombie",
        HP = 1200,
        Attack = 300,
        Speed = 1.6,
        AttackRange = 3,
        AttackInterval = 1,
        Anims = {
            Idle = "rbxassetid://103252167598562",
            Walk = "rbxassetid://110893261547291",
            Bend = "rbxassetid://131459040784217",
            Eat  = "rbxassetid://119641402238824",
            Rise = "rbxassetid://116948729939997",
        },
    },
    ["ScreenDoorZombie"] = {
        Id = "ScreenDoorZombie",
        Name = "Screen Door Zombie",
        HP = 2500,
        Attack = 500,
        Speed = 1.6,
        AttackRange = 3,
        AttackInterval = 1,
        Anims = {
            Idle = "rbxassetid://103252167598562",
            Walk = "rbxassetid://110893261547291",
            Bend = "rbxassetid://131459040784217",
            Eat  = "rbxassetid://119641402238824",
            Rise = "rbxassetid://116948729939997",
        },
    }
}
return ZombieConfig
